Controllers/GrievancePanelController.cs
//--------------------------------------------------------------------
//   Date                 : November, 2023
//    Copyright: (C)2023 by AHT-GROUP, GmbH/SOFTWEL (P) Ltd
//    Email                : support at softwel dot com dot np 
// --------------------------------------------------------------------

// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License (GPL) as published by
// the Free Software Foundation (https://www.fsf.org/); either version 2
// of the License, or (at your option) any later version.


using IntegratedMobileApp.Extensions;
using IntegratedMobileApp.Helpers;
using IntegratedMobileApp.Models.Database;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IntegratedMobileApp.Controllers
{
	[Authorize]
	public class GrievancePanelController : Controller
	{
		ImobappContext DbContext;
		public GrievancePanelController(ImobappContext dbContext)
		{
			DbContext = dbContext;
		}

		public IActionResult Index(int partialViewId = 1)
		{
			ViewData["PartialViewId"] = partialViewId;
			return View();
		}

		public PartialViewResult PostGrievanceView()
		{			
			return PartialView("PostGrievance");
		}

		public PartialViewResult PendingGrievanceView()
		{
			var pmwd = User.GetProvinceMunicipalityWard();
			var grievances = DbContext.TabUsergrivs.Where(it => it.Grivid!.StartsWith(pmwd) && (it.Replyid == null || it.Replyid == "")).OrderByDescending(it => it.Id).ToList();
			if (User.IsWard())
			{
				pmwd = User.GetLocality();
			}
			else if (User.IsMunicipality())
			{
				pmwd = User.GetLocality();
			}
			if (!User.IsAdmin())
			{
				grievances = grievances.Where(it => it.Grivid!.StartsWith(pmwd) && it.Grivreceiver == pmwd && (it.Replyid == null || it.Replyid == "")).OrderByDescending(it => it.Id).ToList();
			}
			ViewData["Grievs"] = grievances;
			return PartialView("PendingGrievance");
		}

		public PartialViewResult RepliedGrievanceView()
		{
			var pmwd = User.GetProvinceMunicipalityWard();
			var grievances = DbContext.TabUsergrivs.Where(it => it.Grivid!.StartsWith(pmwd) && (it.Replyid != null && it.Replyid != "")).OrderByDescending(it => it.Id).ToList();
			if (User.IsWard())
			{
				pmwd = User.GetLocality();
			}
			else if (User.IsMunicipality())
			{
				pmwd = User.GetLocality();
			}
			if (!User.IsAdmin())
			{
				grievances = grievances.Where(it => it.Grivid!.StartsWith(pmwd) && it.Grivreceiver == pmwd && (it.Replyid != null && it.Replyid != "")).OrderByDescending(it => it.Id).ToList();
			}
			ViewData["Grievs"] = grievances;
			return PartialView("RepliedGrievance");
		}

		public IActionResult PostGrievance(string grievTxt, string wardCode, string deptCode)
		{
			var uPMWD = User.GetLocality();
			var uMail = User.GetEmail();
			var uName = User.GetFullName();
			var dt = $"{DateTime.Now:yyyyMMddHHmm}";
			var grievId = $"{uPMWD}-{dt}-{uMail}";
			var grievSender = $"Ward-{uPMWD.Substring(3, 2)}({uName})";
			var grievReceiver = $"{uPMWD[..3]}{wardCode}{deptCode}";
			var griev = new TabUsergriv()
			{
				Grivid = grievId,
				Grivtext = grievTxt,
				Grivsender = grievSender,
				Grivreceiver = grievReceiver,
				Gpic = "-",
				Replyid = $"",
				Replytext = "",
				Rpic = "-"
			};
			DbContext.TabUsergrivs.Add(griev);
			DbContext.SaveChanges();
			return RedirectToAction("Index", new { partialViewId = 1 });
		}

		public IActionResult ForwardGrievance(int Id, string PMWD, string WardCode, string DeptCode)
		{
			var newRecieverId = $"{PMWD[..3]}{WardCode}{DeptCode}";
			var departmentName = WardCode != "00" ? DepartmentHelper.WardDepartmentNep[WardCode] : DepartmentHelper.MunicipalityDepartmentNep[DeptCode];
			var grievance = DbContext.TabUsergrivs.FirstOrDefault(it => it.Id == Id);
			if (grievance != null && DeptCode != "00")
			{
				var grivId = grievance.Grivid!;
				var grivTxt = grievance.Grivtext!;
				var grivSender = grievance.Grivsender!;
				var dt = $"{DateTime.Now:yyyyMMddHHmm}";
				grievance.Replyid = $"{User.GetLocality()}-{dt}-{User.GetEmail()}";
				grievance.Replytext = $"तपाईको गुनासोलाई {departmentName}मा पठाइएको छ ।";
				grievance.Rpic = "-";
				DbContext.TabUsergrivs.Update(grievance);

				var nGrievance = new TabUsergriv()
				{
					Grivid = $"{grivId.Split('-')[0]}-{dt}-{grivId.Split('-')[2]}",
					Grivtext = grivTxt,
					Grivsender = grivSender,
					Grivreceiver = $"{PMWD[..3]}{WardCode}{DeptCode}",
					Gpic = "-",
					Replyid = "",
					Replytext = "",
					Rpic = "-"
				};
				DbContext.TabUsergrivs.Add(nGrievance);
				DbContext.SaveChanges();
			}
			return RedirectToAction("Index", new { partialViewId = 2 });
		}

		public IActionResult Reply2Griev(int Id, string ReplyTxt, string uPMWD, string uMail)
		{
			var griev = DbContext.TabUsergrivs.FirstOrDefault(it => it.Id == Id);
			if (griev != null && (griev.Replyid == null || griev.Replyid == ""))
			{
				var dt = $"{DateTime.Now:yyyyMMddHHmm}";
				griev.Replyid = $"{uPMWD}-{dt}-{uMail}";
				griev.Replytext = ReplyTxt;
				griev.Rpic = "-";
				DbContext.TabUsergrivs.Update(griev);
				DbContext.SaveChanges();
			}
			return RedirectToAction("Index", new { partialViewId = 2 });
		}

		public IActionResult GrievanceStatusChange(int grievId)
		{
			var griev = DbContext.TabUsergrivs.FirstOrDefault(it => it.Id == grievId);
			if (griev != null)
			{
				griev.Status = griev.Status == null || griev.Status == false ? true : false;
				DbContext.TabUsergrivs.Update(griev);
				DbContext.SaveChanges();
			}
			return RedirectToAction("Index", new { partialViewId = 2 });
		}

	}
}

Controllers/LoginController.cs
//--------------------------------------------------------------------
//   Date                 : November, 2023
//    Copyright: (C)2023 by AHT-GROUP, GmbH/SOFTWEL (P) Ltd
//    Email                : support at softwel dot com dot np 
// --------------------------------------------------------------------

// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License (GPL) as published by
// the Free Software Foundation (https://www.fsf.org/); either version 2
// of the License, or (at your option) any later version.

using IntegratedMobileApp.Extensions;
using IntegratedMobileApp.Helpers;
using IntegratedMobileApp.Models.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IntegratedMobileApp.Controllers
{
	public class LoginController : Controller
	{
		ImobappContext DbContext;
		
		public LoginController(ImobappContext dbContext)
		{
			DbContext = dbContext;			
		}

		public IActionResult Index(string ReturnUrl)
		{
			return View("Index", ReturnUrl);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> CheckLogin(string email, string pwd, string returnUrl)
		{
			IActionResult InvalidResponse(string msg)
			{
				ViewData["email"] = email;
				ViewData["Message"] = msg;
				return View("Index", returnUrl);
			}

			var user = DbContext.TabUsers.FirstOrDefault(u => EF.Functions.ILike(u.Umail!, email));
			if (user == null) return InvalidResponse("Incorrect username or password");

			if (user.IsPublic()) return InvalidResponse("Public user cannot login.");			

			bool verified = PasswordHelper.VerifyHashedPassword(pwd, user.Password!); 
			if (verified)
			{
				if (user.Utype![1] == '0')
					return InvalidResponse("User not activated. Please check your email for instructions.");


				await LoginHelper.SignInUser(this.HttpContext, user);
				
				DbContext.TabUsers.Update(user);
				await DbContext.SaveChangesAsync();

				if (!string.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
				{
					return Redirect(returnUrl);
				}
				else
				{
					return RedirectToAction("Index", "AdminPanel");
				}
			}
			else
			{
				return InvalidResponse("Incorrect username or password");
			}
		}

		public async Task<IActionResult> Logout()
		{
			await LoginHelper.SignOutUser(this.HttpContext);
			return RedirectToAction("Index", "Home");
		}
	}
}

Controllers/ServiceAdditionalController.cs
//--------------------------------------------------------------------
//   Date                 : November, 2023
//    Copyright: (C)2023 by AHT-GROUP, GmbH/SOFTWEL (P) Ltd
//    Email                : support at softwel dot com dot np 
// --------------------------------------------------------------------

// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License (GPL) as published by
// the Free Software Foundation (https://www.fsf.org/); either version 2
// of the License, or (at your option) any later version.

using IntegratedMobileApp.Controllers.API;
using IntegratedMobileApp.Extensions;
using IntegratedMobileApp.Helpers;
using IntegratedMobileApp.Models.Database;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IntegratedMobileApp.Controllers
{
	[Authorize]

	public class ServiceAdditionalController : Controller
	{

		ImobappContext DbContext;
		public ServiceAdditionalController(ImobappContext dbContext)
		{
			DbContext = dbContext;
		}

		public IActionResult Index()
		{
			var pm = User.GetProvinceMunicipality();

			var links = DbContext.TabLinks.Where(it => EF.Functions.ILike(it.Lkid!, $"{pm}%")).OrderBy(it => it.Id).ToList();
			ViewData["Links"] = links;

			var polls = DbContext.TabPolls.Where(it => EF.Functions.ILike(it.MunCode!, $"{pm}%")).OrderBy(it => it.Id).ToList();
			ViewData["Polls"] = polls;

			var preTexts = new List<TabPretext>();
			if (User.IsWard())
			{
				preTexts = DbContext.TabPretexts.Where(it => it.Usertype == 2).OrderBy(it => it.Id).ToList();
			} else if (User.IsMunicipality())
			{
				preTexts = DbContext.TabPretexts.Where(it => it.Usertype == 3).OrderBy(it => it.Id).ToList();
			}
			ViewData["PreTexts"] = preTexts;
			return View();

		}

		[HttpPost]
		public IActionResult AddLink([FromForm] int linkCount, [FromForm] string linkNameNep, [FromForm] string linkNameEng, [FromForm] string link)
		{
			if (linkCount == 0) linkCount = Convert.ToInt32($"{User.GetProvinceMunicipality()}00");
			if (linkNameNep != null && linkNameNep != "" && linkNameEng != null && linkNameEng != "" && link != null && link != "")
			{
				if (linkNameEng.IsValiLinkName())
				{
					var lnk = new TabLink()
					{
						Lkid = $"{(linkCount + 1):00}",
						Lnamenep = linkNameNep,
						Lnameeng = linkNameEng,
						Linkdetail = link,
					};
					DbContext.TabLinks.Add(lnk);
					DbContext.SaveChanges();
				}

			}
			return RedirectToAction("Index");
		}

		public IActionResult EditLink(string linkId, string linkNameNep, string linkNameEng, string link)
		{
			var lnk = DbContext.TabLinks.FirstOrDefault(it => it.Lkid == linkId);
			if (lnk != null && linkNameNep != null && linkNameNep != "" && linkNameEng != null && linkNameEng != "" && link != null && link != "")
			{
				if (linkNameEng.IsValiLinkName())
				{
					lnk.Lnamenep = linkNameNep;
					lnk.Lnameeng = linkNameEng;
					lnk.Linkdetail = link;
					DbContext.TabLinks.Update(lnk);
					DbContext.SaveChanges();
				}
			}
			return RedirectToAction("Index");
		}

		public IActionResult DeleteLink(string linkId)
		{
			var lnk = DbContext.TabLinks.FirstOrDefault(it => it.Lkid == linkId);
			if (lnk != null)
			{
				DbContext.TabLinks.Remove(lnk);
				DbContext.SaveChanges();
			}
			return RedirectToAction("Index");
		}


		[HttpPost]
		public IActionResult AddPoll([FromForm] string qText, [FromForm] string[] oTexts)
		{
			if (qText != null && oTexts != null && oTexts!.Length > 0)
			{
				var polls = new List<TabPoll>();
				var munCode = User.GetProvinceMunicipality();
				var qUuid = Guid.NewGuid().ToString();
				foreach (var oText in oTexts)
				{
					var poll = new TabPoll()
					{
						MunCode = munCode,
						QUuid = qUuid,
						QText = qText,
						OUuid = Guid.NewGuid().ToString(),
						OText = oText
					};
					polls.Add(poll);
				}
				DbContext.TabPolls.AddRange(polls);
				DbContext.SaveChanges();
			}
			return RedirectToAction("Index");
		}


		[HttpPost]
		public IActionResult EditPoll([FromForm] string qUuid, [FromForm] string qText, [FromForm] string[] oTexts)
		{
			if (qText != null && oTexts != null && oTexts!.Length > 0)
			{
				var polls = DbContext.TabPolls.Where(it=>it.QUuid == qUuid).OrderBy(it=>it.Id).ToList();
				if(polls != null && polls.Count > 0)
				{
					DbContext.TabPolls.RemoveRange(polls);
					polls = new List<TabPoll>();
					var munCode = User.GetProvinceMunicipality();
					foreach (var oText in oTexts)
					{
						var poll = new TabPoll()
						{
							MunCode = munCode,
							QUuid = qUuid,
							QText = qText,
							OUuid = Guid.NewGuid().ToString(),
							OText = oText
						};
						polls.Add(poll);
					}
					DbContext.TabPolls.AddRange(polls);
					DbContext.SaveChanges();
				}
			}
			return RedirectToAction("Index");
		}

		[HttpPost]
		public IActionResult DeletePoll([FromForm] string qUuid)
		{
			if (qUuid != null)
			{
				var polls = DbContext.TabPolls.Where(it => it.QUuid == qUuid).OrderBy(it => it.Id).ToList();
				if (polls != null && polls.Count > 0)
				{
					DbContext.TabPolls.RemoveRange(polls);					
					DbContext.SaveChanges();
				}
			}
			return RedirectToAction("Index");
		}

		[HttpPost]
		public IActionResult EditPollOption([FromForm] string oUuid, [FromForm] string oText)
		{
			if (oUuid != null && oText != null)
			{
				var poll = DbContext.TabPolls.FirstOrDefault(it => it.OUuid == oUuid);
				if (poll != null)
				{
					poll.OText = oText;
					DbContext.TabPolls.Update(poll);
					DbContext.SaveChanges();
				}
			}
			return RedirectToAction("Index");
		}

		[HttpPost]
		public IActionResult DeletePollOption([FromForm] string oUuid)
		{
			if (oUuid != null)
			{
				var poll = DbContext.TabPolls.FirstOrDefault(it => it.OUuid == oUuid);
				if (poll != null )
				{															
					DbContext.TabPolls.Remove(poll);
					DbContext.SaveChanges();					
				}
			}
			return RedirectToAction("Index");
		}


		public IActionResult AddPreText(string nepPreText, string engPreText)
		{
			if (nepPreText != null && nepPreText != "" && engPreText != null && engPreText != "")
			{
				var userType = User.IsWard() ? 2 : User.IsMunicipality() ? 3 : User.IsAdmin() ? 4 : 0;
				var preText = new TabPretext()
				{				
					Neptext = nepPreText,
					Engtext = engPreText,
					Usertype = userType
				};
				DbContext.TabPretexts.Add(preText);
				DbContext.SaveChanges();
			}
			return RedirectToAction("Index");
		}

		public IActionResult EditPreText(int Id, string nepPreText, string engPreText)
		{
			var preText  = DbContext.TabPretexts.FirstOrDefault(it => it.Id == Id);
			if (preText != null &&  nepPreText != null && nepPreText != "" && engPreText != null && engPreText != "")
			{				
				preText.Neptext = nepPreText;
				preText.Engtext = engPreText;
				DbContext.TabPretexts.Update(preText);
				DbContext.SaveChanges();
			}
			return RedirectToAction("Index");
		}

		public IActionResult DeletePreText(int Id)
		{
			var preText = DbContext.TabPretexts.FirstOrDefault(it => it.Id == Id);
			if (preText != null)
			{			
				DbContext.TabPretexts.Remove(preText);
				DbContext.SaveChanges();
			}
			return RedirectToAction("Index");
		}
	}
}

Views/Shared/_Layout.cshtml
@*
//--------------------------------------------------------------------
//   Date                 : November, 2023
//    Copyright: (C)2023 by AHT-GROUP, GmbH/SOFTWEL (P) Ltd
//    Email                : support at softwel dot com dot np
// --------------------------------------------------------------------

// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License (GPL) as published by
// the Free Software Foundation (https://www.fsf.org/); either version 2
// of the License, or (at your option) any later version.
*@
@using IntegratedMobileApp.Extensions;
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - IMA</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/IntegratedMobileApp.styles.css" asp-append-version="true" />
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
	<script src="~/js/tus.min.js"></script>
	@* <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>*@
</head>
<style>
	.container {
		max-width: unset;
		width: 100%;
		padding-left: 3rem;
		padding-right: 3rem;
		margin: 0 auto;
	}
</style>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Integrated Mobile App</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						@if (!User.IsPublic())
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="AdminPanel" asp-action="Index">Admin Panel</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="GrievancePanel" asp-action="Index">Grievance Panel</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="ServiceAdditional" asp-action="Index">Additional Service Panel</a>
							</li>
						}
					</ul>
					<ul class="navbar-nav">
						@if (User.Identity?.IsAuthenticated ?? false)
						{
							<li class="nav-item dropdown">
								<a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
									@User.GetEmail()
									<span class="caret"></span>
								</a>
								<ul class="dropdown-menu dropdown-menu-end">
									<li>
										<a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Logout">Log Out</a>
									</li>
								</ul>
							</li>
						}
						else
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
							</li>
						}
					</ul>
				</div>
			</div>
		</nav>
	</header>

	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted d-flex justify-content-around">
		<div class="container">
			&copy; 2023 - IntegratedMobileApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
		<div class="container position-relative">
			<div class="position-absolute bottom-0 end-0" style="margin-right:10px">
				<span style="margin-right:1rem;">Developed By <a href="http://softwel.com.np/" target="_blank">Softwel (P) Ltd.</a> </span>				
			</div>
		</div>
	</footer>

	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)	
</body>
</html>